# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b43cdc6e5643cac15b825cb43d93d5b6d6a1b3b8320d118aafcdadb60c75da20de3344dcea6b40f429cf23a53f8593a815001bb0676e75a6754e6c7308a145cf

test:
  secret_key_base: c7d3e717ee3b42332ddd2d25ea540d8eaa167b96010c967585927c0987c58c0dc7c6156d7cb352bc0bc71395494793b012ac41c720c1b4c360446cfb7cd4f82d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
